anguage: node_js

node_js: 
  - 10

cache:
  directories:
  - node_modules
before_install:

  - npm install -g hexo-cli@3.1.0

install:
  - npm install

script:
  - hexo clean 
  - hexo g 

after_script:
  - cd ./public
  - git init
  - git config user.name "Major9506"
  - git config user.email "1293963839@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${travisCI}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/Major9506/Major9506.github.io.git
  
notifications:
  email:
    - 1293963839@qq.com
  on_success: change
  on_failure: always